@echo off

echo Building basic test program with static linking...
gcc -static -I. -L./build ./tests/test.c -o ./tests/test_static.exe -ldlfcn

echo Building basic test program with dynamic linking...
gcc -I. -L./build ./tests/test.c -o ./tests/test_dynamic.exe -ldlfcn

: echo Building dladdr test program with static linking...
echo Building dladdr test program (used static linking)...
gcc -static -I. -L./build ./tests/test-dladdr.c -o ./tests/test-dladdr.exe -ldlfcn

: echo Building dladdr test program with dynamic linking...
: gcc -I. -L./build ./tests/test-dladdr.c -o ./tests/test-dladdr_dynamic.exe -ldlfcn

echo Building test DLL 1...
gcc -I. -L./build -fPIC -shared ./tests/testdll.c -o ./tests/testdll.dll

echo Building test DLL 2 (used static dlfcn linking)...
gcc -I. -L./build -fPIC -shared ./tests/testdll2.c -o ./tests/testdll2.dll -static -ldlfcn

echo Building test DLL 3...
gcc -I. -L./build -fPIC -shared ./tests/testdll3.c -o ./tests/testdll3.dll

echo Finished successfully.